# Generated by Django 2.0.13 on 2019-05-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='checked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
